SELECT TOP 100 * FROM [dbo].[tblDeptErrorLog] ORDER BY [dtCreated] DESC
SELECT * FROM [dbo].[tblTender] WHERE [nTenderID]=77396

SELECT * FROM [dbo].[tblLogin] WHERE [sUserName]='testuser8'

select * FROM tblSupplierPreQualifications WHERE [nProcurementID]=12479 AND nsupplieruserid=5443

SELECT * FROM tblSupplierBidProfile WHERE [nProcurementID]=278

--delete all inserted records if error get when click on edit icon at bidder side
--DELETE tblSupplierPreQualifications WHERE [nProcurementID]=12479 AND nsupplieruserid=6450



id:77398 for testuser6

77396 for testuser6 and testuser8

