----------------------------------------------------------------
SELECT * FROM [dbo].[tblDepartment] WHERE [nDepartmentID]=492
SELECT * FROM [dbo].[tblDepartment] WHERE [nDepartmentID]=491
SELECT * FROM [dbo].[tblDepartment] WHERE [nDepartmentID]=490
SELECT * FROM [dbo].[tblDepartment] WHERE [nDepartmentID]=445
SELECT * FROM [dbo].[tblDepartment] WHERE [nDepartmentID]=435
--------------------------------------------------------------------
SELECT * FROM [dbo].[tblDepartment] WHERE [nDepartmentID]=389
SELECT * FROM [dbo].[tblDepartment] WHERE [nDepartmentID]=386
SELECT * FROM [dbo].[tblDepartment] WHERE [nDepartmentID]=385

------------------------------------------------------------------
SELECT * FROM [dbo].[tblDepartment] WHERE [nDepartmentID]=445
SELECT * FROM [dbo].[tblDepartment] WHERE [nDepartmentID]=435